ALTER TABLE audit_log ADD COLUMN user_id BIGINT NULL;
ALTER TABLE audit_log ADD COLUMN user_name VARCHAR(100) NULL;
ALTER TABLE audit_log ADD COLUMN user_role VARCHAR(50) NULL;
ALTER TABLE audit_log ADD COLUMN action VARCHAR(100) NULL;
ALTER TABLE audit_log ADD COLUMN project_name VARCHAR(255) NULL;
ALTER TABLE audit_log ADD COLUMN document_name VARCHAR(255) NULL;
ALTER TABLE audit_log ADD COLUMN document_version VARCHAR(50) NULL;
ALTER TABLE audit_log ADD COLUMN input_type VARCHAR(100) NULL;
